init: 
- git config --global core.autocrlf input 
install:
- npm -g install npm@2
- set PATH=%APPDATA%\npm;%PATH%
- npm install gulp bower -g
build_script: 
- node --version 
- npm --version 
- bower --version 
- npm install 
- bower install 

test: off
deploy: off
